"""Main client module for iRODS HTTP API interactions."""

import requests

from irods_http_client import common
from irods_http_client.collection_operations import Collections
from irods_http_client.data_object_operations import DataObjects
from irods_http_client.query_operations import Queries
from irods_http_client.resource_operations import Resources
from irods_http_client.rule_operations import Rules
from irods_http_client.ticket_operations import Tickets
from irods_http_client.user_group_operations import UsersGroups
from irods_http_client.zone_operations import Zones


class IRODSHTTPClient:
	"""HTTP client for interacting with iRODS via REST API."""

	def __init__(self, url_base: str):
		"""Get the base url from the user to initialize a client instance."""
		self.url_base = url_base
		self.token = None

		self.collections = Collections(url_base)
		self.data_objects = DataObjects(url_base)
		self.queries = Queries(url_base)
		self.resources = Resources(url_base)
		self.rules = Rules(url_base)
		self.tickets = Tickets(url_base)
		self.users_groups = UsersGroups(url_base)
		self.zones = Zones(url_base)

	def authenticate(self, username: str = "", password: str = ""):
		"""
		Take user credentials as parameters and attempts to authenticate and retrieve a token.

		Args:
		    username: The username of the user to be authenticated.
		    password: The password of the user to be authenticated.

		Returns:
		    User token generated by the server.

		Raises:
		    TypeError: If any parameter is not a string.
		    RuntimeError: If authentication fails.
		"""
		if not isinstance(username, str):
			raise TypeError("username must be a string")
		if not isinstance(password, str):
			raise TypeError("password must be a string")

		r = requests.post(self.url_base + "/authenticate", auth=(username, password), timeout=30)

		if r.status_code / 100 == 2:  # noqa: PLR2004
			if self.token is None:
				self.set_token(r.text)
			return r.text
		raise RuntimeError("Failed to authenticate: " + str(r.status_code))

	def set_token(self, token: str):
		"""
		Set the token to be used when making requests.

		Args:
		    token: The token to be set.

		Raises:
		    TypeError: If token is not a string.
		"""
		if not isinstance(token, str):
			raise TypeError("token must be a string")
		self.token = token

		self.collections.token = token
		self.data_objects.token = token
		self.queries.token = token
		self.resources.token = token
		self.rules.token = token
		self.tickets.token = token
		self.users_groups.token = token
		self.zones.token = token

	def get_token(self):
		"""
		Return the authentication token currently in use.

		Returns:
		    The authentication token currently in use.
		"""
		return self.token

	def info(self):
		"""
		Give general information about the iRODS server.

		Returns
		- A dict containing the HTTP status code and iRODS response.
		- The iRODS response is only valid if no error occurred during HTTP communication.
		"""
		headers = {
			"Authorization": "Bearer " + self.token,
		}

		r = requests.get(self.url_base + "/info", headers=headers, timeout=30)
		return common.process_response(r)
